# -*- coding: utf-8 -*-
"""
load_grids_pickle.py
Load voxel grids generated from MD snapshots with data augmentation.
This script loads pickle files generated by store_grids_pickle.py and provides
basic data loading and verification for machine learning training.

The script supports both pure solvent systems (e.g., water_pure) and mixed 
solvent systems (e.g., methanol_240_water_960) by automatically detecting
and loading the corresponding CSV files and pickle files.

Classes:
    VoxelGridsLoader: Main class for loading voxel grid data

Supported Systems:
    - Pure water systems: water_pure-hydrophilic, water_pure-hydrophobic
    - Mixed methanol-water systems: methanol_X_water_Y-hydrophilic/hydrophobic
      where X and Y represent the number of molecules in the simulation
"""

## Importing Necessary Modules
import os
import glob
import warnings
## Importing Pandas
import pandas as pd
## Importing Numpy
import numpy as np
## Importing Pickle
import pickle
# Import custom modules
from core.path import get_paths
from core.global_vars import ZEOLITE_TYPES, ADSORBATES_BY_ENV

class VoxelGridsLoader:
    """
    A simple class to load and verify voxel grid data from pickle files.
    
    This class loads pickle files for specified zeolite types and adsorbates,
    and provides basic verification and summary functions.
    """
    
    def __init__(self,
                 zeolite_types,
                 adsorbates_by_env,
                 box_grids_size=16.0,
                 box_increment=0.8,
                 num_features=28,
                 verbose=True,
                 ):
        """
        Initialize the VoxelGridsLoader.
        
        INPUTS:
            zeolite_types: list, zeolite types to load
            adsorbates_by_env: dict, environments and their adsorbates
            box_grids_size: float, box size in Angstrom
            box_increment: float, voxel size in Angstrom
            num_features: int, number of feature channels
            verbose: bool, whether to print detailed information
        """
        self.zeolite_types = zeolite_types
        self.adsorbates_by_env = adsorbates_by_env
        self.box_grids_size = box_grids_size
        self.box_increment = box_increment
        self.num_features = num_features
        self.verbose = verbose
        
        # Calculate expected grid dimensions
        self.max_bin_num = int(box_grids_size / box_increment)
        self.expected_shape = (self.max_bin_num, self.max_bin_num, self.max_bin_num, self.num_features)
        self.voxel_shape_str = f"{self.max_bin_num}_{self.max_bin_num}_{self.max_bin_num}_{self.num_features}"
        
        # Dataset directory
        self.dataset_dir = get_paths('dataset_cnn')
        
        if not os.path.exists(self.dataset_dir):
            raise FileNotFoundError(f"Dataset directory not found: {self.dataset_dir}")
        
        # Initialize containers
        self.loaded_data = {}  # Store loaded pickle data
        self.all_pickle_files = []  # List of loaded filenames
        self.feature_names = None  # Will be set during data loading
        self.feature_channels = None  # Will store feature channel mapping for molecular interactions
        
        if self.verbose:
            print(f"\n--- VoxelGridsLoader initialized")
            print(f"    Dataset directory: {self.dataset_dir}")
            print(f"    Expected grid shape: {self.expected_shape}")
            print(f"    Zeolite types: {self.zeolite_types}")
            # Print each key-value pair on a separate line, aligned
            print("    Adsorbates by environment:")
            max_key_len = max(len(str(k)) for k in self.adsorbates_by_env)
            for env, ads_list in self.adsorbates_by_env.items():
                env_type = "Mixed solvent" if "methanol" in env and "water" in env else "Pure solvent"
                print(f"--- {env.ljust(max_key_len)} : {ads_list} ({env_type})")

    
    def load_label_data(self):
        """
        Load label data from specific CSV files in the database directory.
        Only loads water_pure-hydrophilic.csv and water_pure-hydrophobic.csv files.
        
        Returns:
            pandas.DataFrame: Combined label data from the specified CSV files
        """
        database_path = get_paths("database_path")
        combined_data = []
        
        if self.verbose:
            print(f"\n--- Loading label data from CSV files ---")
        
        # Only load these specific files
        target_files = [f'{env}.csv' for env in self.adsorbates_by_env.keys()]
        
        for csv_filename in target_files:
            csv_path = os.path.join(database_path, csv_filename)
            
            if os.path.exists(csv_path):
                try:
                    # Load CSV with all required columns directly
                    df_env = pd.read_csv(csv_path, usecols=['zeolite', 'environment', 'adsorbate', 'snapshot', 'intE'])
                    
                    # Create env_adsorbate column immediately after loading
                    df_env['env_adsorbate'] = df_env['environment'] + '-' + df_env['adsorbate']
                    
                    # Reorder columns to desired sequence
                    df_env = df_env[['zeolite', 'environment', 'adsorbate', 'env_adsorbate', 'snapshot', 'intE']]
                    
                    combined_data.append(df_env)
                    
                    if self.verbose:
                        print(f"    Loaded {len(df_env)} records from {csv_filename}")
                        print(f"        Adsorbates: {df_env['adsorbate'].nunique()}")
                        print(f"        Snapshots: {df_env['snapshot'].min()}-{df_env['snapshot'].max()}")
                        
                except Exception as e:
                    print(f"    Error loading {csv_path}: {e}")
            else:
                print(f"    Warning: File not found: {csv_path}")
        
        if not combined_data:
            print("    No valid label data found")
            return pd.DataFrame()
        
        # Combine all data
        df_combined = pd.concat(combined_data, ignore_index=True)
        
        if self.verbose:
            print(f"\n--- Combined label data summary ---")
            print(f"    Total records: {len(df_combined)}")
            print(f"    Unique environment-adsorbate combinations: {df_combined['env_adsorbate'].nunique()}")
            print(f"    Unique environments: {df_combined['environment'].nunique()}")
            print(f"    Available environments: {sorted(df_combined['environment'].unique())}")
            print(f"    Energy range: [{df_combined['intE'].min():.3f}, {df_combined['intE'].max():.3f}]")
            print("")
        
        return df_combined
    
    def load_all_pickle_files(self):
        """Load all specified pickle files and simplify data structure."""
        if self.verbose:
            print(f"\n--- Loading all specified pickle files ---")
        
        # Load label data first
        df_labels = self.load_label_data()
        
        total_loaded = 0
        
        for zeolite in self.zeolite_types:
            for env, adsorbates in self.adsorbates_by_env.items():
                solvent_type, pore_type = env.split('-')
                
                for adsorbate in adsorbates:
                    # Generate expected filename pattern using calculated shape
                    pattern = f"{zeolite}-{solvent_type}-{pore_type}-{adsorbate}-size_{self.box_grids_size:.1f}-box_{self.box_increment:.1f}-shape_{self.voxel_shape_str}.pkl"
                    
                    # Look for subdirectory using calculated shape
                    subdir_name = f"size_{self.box_grids_size:.1f}-box_{self.box_increment:.1f}-shape_{self.voxel_shape_str}"
                    subdir_path = os.path.join(self.dataset_dir, subdir_name)
                    
                    file_found = False
                    if os.path.isdir(subdir_path):
                        # Look for the specific file in this subdirectory
                        file_path = os.path.join(subdir_path, pattern)
                        
                        if os.path.exists(file_path):
                            filename = os.path.basename(file_path)
                            
                            if self.verbose:
                                print(f"  - Loading: {subdir_name}/{filename}")
                            
                            # Load pickle file
                            with open(file_path, 'rb') as f:
                                raw_data = pickle.load(f)
                            
                            # Simplify data structure
                            key = f"{zeolite}-{env}-{adsorbate}"
                            
                            # Collect all augmented grids
                            all_grids = []
                            all_labels = []
                            snapshot_indices = []
                            voxel_ids = []  # Track rotation index (1-24) for each grid
                            
                            # NEW: Updated to match load_pickles.py structure
                            for snap_idx, snap_data in raw_data['snapshots'].items():
                                # Handle the new data structure with 'augmented_data' list of dicts
                                if 'augmented_data' in snap_data:
                                    # Extract voxel grids from the list of dictionaries
                                    augmented_items = snap_data['augmented_data']
                                    grids = [item['voxel_grid'] for item in augmented_items]
                                    rotation_names = [item['rotation_name'] for item in augmented_items]
                                    
                                    all_grids.extend(grids)
                                    
                                    # Get labels for this snapshot from CSV data if available
                                    if not df_labels.empty:
                                        # Find corresponding label
                                        label_row = df_labels[
                                            (df_labels['zeolite'] == zeolite) &
                                            (df_labels['environment'] == env) &
                                            (df_labels['adsorbate'] == adsorbate) &
                                            (df_labels['snapshot'] == snap_idx)
                                        ]
                                        if not label_row.empty:
                                            # Convert np.float64 to Python float
                                            label_value = float(label_row['intE'].iloc[0])
                                        else:
                                            label_value = None
                                    else:
                                        # Fallback: use target_interaction_energy from snapshot data
                                        label_value = snap_data.get('target_interaction_energy', None)
                                    
                                    # Replicate label for all augmented grids from this snapshot
                                    num_grids = len(grids)
                                    all_labels.extend([label_value] * num_grids)
                                    snapshot_indices.extend([snap_idx] * num_grids)
                                    
                                    # Add voxel_id (1-24) for each rotation in this snapshot
                                    voxel_ids.extend(list(range(1, num_grids + 1)))
                                    
                                else:
                                    print(f"    Warning: Snapshot {snap_idx} has unknown data structure, skipping")
                                    continue
                                
                            # Create simplified data structure
                            # Get features based on data format
                            if 'features' in raw_data['metadata']:
                                # Original format (15 channels)
                                features = raw_data['metadata']['features']
                            elif 'atomic_features' in raw_data['metadata']:
                                # For 28-channel grids, use the explicit channel mapping when available.
                                if 'feature_channel_mapping' in raw_data['metadata'] and self.num_features == 28:
                                    # Use the real feature channel mapping for 28 channels
                                    feature_mapping = raw_data['metadata']['feature_channel_mapping']
                                    
                                    # Save feature channel mapping for molecular interaction analysis
                                    if self.feature_channels is None:
                                        self.feature_channels = feature_mapping.copy()
                                    
                                    # Sort by channel number to get features in correct order
                                    features = [None] * 28
                                    for feature_name, channel_list in feature_mapping.items():
                                        if channel_list and len(channel_list) > 0:
                                            channel_idx = channel_list[0]  # Get first channel index
                                            if 0 <= channel_idx < 28:
                                                features[channel_idx] = feature_name
                                    
                                    # Fill any missing features with generic names
                                    for i in range(28):
                                        if features[i] is None:
                                            features[i] = f"feature_{i}"
                                else:
                                    # Fallback: use atomic_features if available
                                    atomic_features = raw_data['metadata']['atomic_features']
                                    features = atomic_features
                            else:
                                # Fallback: generate generic feature names
                                features = [f"feature_{i}" for i in range(self.num_features)]
                                
                            simplified_data = {
                                'voxel_grids': all_grids,  # List of 240 voxel grids
                                'labels': all_labels,      # List of 240 corresponding labels
                                'snapshot_indices': snapshot_indices,  # Which snapshot each grid came from
                                'voxel_ids': voxel_ids,   # Rotation index (1-24) for each grid
                                'adsorbate': raw_data['adsorbate'],
                                'zeolite_type': raw_data['metadata']['zeolite_type'],
                                'environment': env,
                                'grid_shape': raw_data['metadata']['grid_shape'],
                                'features': features,  # Use the determined features
                                'total_grids': len(all_grids),
                                'snapshots_count': raw_data['metadata']['snapshots_count']
                            }
                            
                            self.loaded_data[key] = simplified_data
                            self.all_pickle_files.append(f"{subdir_name}/{filename}")
                            total_loaded += 1
                            file_found = True
                            
                            # Extract feature names from the first loaded dataset
                            if self.feature_names is None:
                                # Try different ways to extract feature names based on data format
                                if 'features' in raw_data['metadata']:
                                    # Original format (15 channels)
                                    self.feature_names = raw_data['metadata']['features']
                                    if self.verbose:
                                        print(f"    Feature names extracted (original format): {self.feature_names}")
                                elif 'atomic_features' in raw_data['metadata']:
                                    # Fall back to the ordered atomic-feature list for 28-channel grids.
                                    if 'feature_channel_mapping' in raw_data['metadata'] and self.num_features == 28:
                                        # Use the real feature channel mapping for 28 channels
                                        feature_mapping = raw_data['metadata']['feature_channel_mapping']
                                        
                                        # Save feature channel mapping for molecular interaction analysis
                                        if self.feature_channels is None:
                                            self.feature_channels = feature_mapping.copy()
                                        
                                        # Sort by channel number to get features in correct order
                                        self.feature_names = [None] * 28
                                        for feature_name, channel_list in feature_mapping.items():
                                            if channel_list and len(channel_list) > 0:
                                                channel_idx = channel_list[0]  # Get first channel index
                                                if 0 <= channel_idx < 28:
                                                    self.feature_names[channel_idx] = feature_name
                                        
                                        # Fill any missing features with generic names
                                        for i in range(28):
                                            if self.feature_names[i] is None:
                                                self.feature_names[i] = f"feature_{i}"
                                        
                                        if self.verbose:
                                            print(f"    Feature names extracted from feature_channel_mapping (28 channels): {len(self.feature_names)} features")
                                    else:
                                        # Fallback: use atomic_features if available
                                        atomic_features = raw_data['metadata']['atomic_features']
                                        self.feature_names = atomic_features
                                        if self.verbose:
                                            print(f"    Feature names extracted from atomic_features: {self.feature_names}")
                                else:
                                    # Fallback: generate generic feature names
                                    self.feature_names = [f"feature_{i}" for i in range(self.num_features)]
                                    if self.verbose:
                                        print(f"    Generated generic feature names: {len(self.feature_names)} features")
                            
                            if self.verbose:
                                valid_labels = sum(1 for label in all_labels if label is not None)
                                print(f"    Successfully loaded: {len(all_grids)} grids, {valid_labels}/{len(all_labels)} labels")
                    
                    if not file_found:
                        print(f"  Warning: No file found for {zeolite}-{env}-{adsorbate}")
        
        if self.verbose:
            print(f"\n--- Total loaded datasets: {total_loaded}")
        
        return self.loaded_data
    
    def verify_loaded_data(self):
        """
        Verify the integrity of all loaded datasets with comprehensive checks.
        
        This function validates:
        1. Basic structure (grid count, label count, shapes)
        2. Snapshot structure (10 snapshots per adsorbate)
        3. Augmentation structure (24 grids per snapshot)
        4. Label consistency (same label for all 24 grids from same snapshot)
        5. Voxel ID correctness (rotation indices 1-24 for each snapshot)
        """
        if not self.loaded_data:
            print("No data loaded yet. Call load_all_pickle_files() first.")
            return {}
        
        print(f"\n=== Comprehensive Data Verification ({len(self.loaded_data)} datasets) ===")
        
        verification_results = {}
        
        for key, data in self.loaded_data.items():
            result = {
                'status': 'PASS',
                'issues': [],
                'warnings': [],
                'summary': {}
            }
            
            try:
                # Extract data components
                voxel_grids = data['voxel_grids']
                labels = data['labels']
                snapshot_indices = data['snapshot_indices']
                voxel_ids = data.get('voxel_ids', [])
                expected_shape = data['grid_shape']
                snapshots_count = data['snapshots_count']
                
                # === BASIC STRUCTURE CHECKS ===
                
                # Check grid count matches label count
                if len(voxel_grids) != len(labels):
                    result['issues'].append(f"Grid count ({len(voxel_grids)}) ≠ label count ({len(labels)})")
                    result['status'] = 'FAIL'
                
                # Check grid count matches snapshot indices count
                if len(voxel_grids) != len(snapshot_indices):
                    result['issues'].append(f"Grid count ({len(voxel_grids)}) ≠ snapshot indices count ({len(snapshot_indices)})")
                    result['status'] = 'FAIL'
                
                # Check voxel_ids count if available
                if voxel_ids and len(voxel_grids) != len(voxel_ids):
                    result['issues'].append(f"Grid count ({len(voxel_grids)}) ≠ voxel IDs count ({len(voxel_ids)})")
                    result['status'] = 'FAIL'
                
                # === GRID SHAPE CHECKS ===
                shape_issues = 0
                for i, grid in enumerate(voxel_grids):
                    if grid.shape != expected_shape:
                        if shape_issues < 3:  # Only report first few
                            result['issues'].append(f"Grid {i} shape mismatch: expected {expected_shape}, got {grid.shape}")
                        shape_issues += 1
                        result['status'] = 'FAIL'
                
                if shape_issues > 3:
                    result['issues'].append(f"... and {shape_issues-3} more shape mismatches")
                
                # === ADSORBATE STRUCTURE CHECKS ===
                
                # Check expected total grids (should be 240 = 10 snapshots × 24 augmentations)
                expected_total = snapshots_count * 24
                if len(voxel_grids) != expected_total:
                    result['issues'].append(f"Total grid count mismatch: expected {expected_total} (={snapshots_count}×24), found {len(voxel_grids)}")
                    result['status'] = 'FAIL'
                
                # === SNAPSHOT STRUCTURE CHECKS ===
                
                # Group data by snapshot
                snapshot_groups = {}
                for i, snap_idx in enumerate(snapshot_indices):
                    if snap_idx not in snapshot_groups:
                        snapshot_groups[snap_idx] = {
                            'grids': [],
                            'labels': [],
                            'voxel_ids': [],
                            'indices': []
                        }
                    snapshot_groups[snap_idx]['grids'].append(voxel_grids[i])
                    snapshot_groups[snap_idx]['labels'].append(labels[i])
                    snapshot_groups[snap_idx]['indices'].append(i)
                    if voxel_ids:
                        snapshot_groups[snap_idx]['voxel_ids'].append(voxel_ids[i])
                
                # Check snapshot count and indices
                unique_snapshots = sorted(snapshot_groups.keys())
                expected_snapshots = list(range(1, snapshots_count + 1))
                
                if len(unique_snapshots) != snapshots_count:
                    result['issues'].append(f"Snapshot count mismatch: expected {snapshots_count}, found {len(unique_snapshots)}")
                    result['status'] = 'FAIL'
                
                if unique_snapshots != expected_snapshots:
                    result['issues'].append(f"Snapshot indices mismatch: expected {expected_snapshots}, found {unique_snapshots}")
                    result['status'] = 'FAIL'
                
                # === AUGMENTATION STRUCTURE CHECKS ===
                
                label_consistency_issues = 0
                voxel_id_issues = 0
                
                for snap_idx, snap_data in snapshot_groups.items():
                    snap_grids = snap_data['grids']
                    snap_labels = snap_data['labels']
                    snap_voxel_ids = snap_data['voxel_ids']
                    
                    # Check 24 grids per snapshot
                    if len(snap_grids) != 24:
                        result['issues'].append(f"Snapshot {snap_idx}: expected 24 grids, found {len(snap_grids)}")
                        result['status'] = 'FAIL'
                    
                    # Check label consistency within snapshot
                    unique_labels = list(set(snap_labels))
                    if len(unique_labels) > 1:
                        result['issues'].append(f"Snapshot {snap_idx}: inconsistent labels {unique_labels} (should be identical)")
                        result['status'] = 'FAIL'
                        label_consistency_issues += 1
                    elif len(unique_labels) == 0 or unique_labels[0] is None:
                        result['warnings'].append(f"Snapshot {snap_idx}: missing label")
                    
                    # Check voxel IDs (rotation indices) if available
                    if snap_voxel_ids:
                        expected_voxel_ids = list(range(1, 25))  # 1-24
                        actual_voxel_ids = sorted(snap_voxel_ids)
                        if actual_voxel_ids != expected_voxel_ids:
                            result['issues'].append(f"Snapshot {snap_idx}: incorrect voxel IDs, expected 1-24, found {actual_voxel_ids[:5]}...{actual_voxel_ids[-5:]}")
                            result['status'] = 'FAIL'
                            voxel_id_issues += 1
                
                # === LABEL STATISTICS ===
                
                valid_labels = sum(1 for label in labels if label is not None)
                unique_label_values = len(set(label for label in labels if label is not None))
                
                # Check if we have the expected number of unique labels (should equal number of snapshots)
                if unique_label_values != snapshots_count and valid_labels > 0:
                    result['warnings'].append(f"Expected {snapshots_count} unique labels, found {unique_label_values}")
                
                # === SUMMARY ===
                
                result['summary'] = {
                    'total_grids': len(voxel_grids),
                    'valid_labels': valid_labels,
                    'unique_snapshots': len(unique_snapshots),
                    'grids_per_snapshot': len(voxel_grids) // len(unique_snapshots) if unique_snapshots else 0,
                    'unique_label_values': unique_label_values,
                    'grid_shape': expected_shape,
                    'adsorbate': data['adsorbate'],
                    'environment': data['environment'],
                    'label_consistency_issues': label_consistency_issues,
                    'voxel_id_issues': voxel_id_issues
                }
                
            except Exception as e:
                result['status'] = 'ERROR'
                result['issues'].append(f"Verification error: {str(e)}")
            
            verification_results[key] = result
            
            # Print detailed status
            if result['status'] == 'PASS':
                status_symbol = "✅"
                status_color = "PASS"
            elif result['status'] == 'FAIL':
                status_symbol = "❌"
                status_color = "FAIL"
            else:
                status_symbol = "⚠️"
                status_color = "ERROR"
            
            summary = result['summary']
            print(f"  {status_symbol} {key}: {status_color}")
            print(f"    📊 {summary['total_grids']} grids, {summary['unique_snapshots']} snapshots, {summary['grids_per_snapshot']} grids/snapshot")
            print(f"    🏷️  {summary['valid_labels']}/{summary['total_grids']} valid labels, {summary['unique_label_values']} unique values")
            
            if result['issues']:
                print(f"    🚨 Issues ({len(result['issues'])}):")
                for issue in result['issues']:
                    print(f"      - {issue}")
            
            if result['warnings']:
                print(f"    ⚠️  Warnings ({len(result['warnings'])}):")
                for warning in result['warnings']:
                    print(f"      - {warning}")
        
        # Overall summary
        total_datasets = len(verification_results)
        passed_datasets = sum(1 for r in verification_results.values() if r['status'] == 'PASS')
        failed_datasets = sum(1 for r in verification_results.values() if r['status'] == 'FAIL')
        error_datasets = sum(1 for r in verification_results.values() if r['status'] == 'ERROR')
        
        print(f"\n=== Verification Summary ===")
        print(f"  📋 Total datasets: {total_datasets}")
        print(f"  ✅ Passed: {passed_datasets}")
        print(f"  ❌ Failed: {failed_datasets}")
        print(f"  ⚠️  Errors: {error_datasets}")
        
        if passed_datasets == total_datasets:
            print(f"  🎉 All datasets passed comprehensive verification!")
        else:
            print(f"  ⚠️  {failed_datasets + error_datasets} datasets have issues")
        
        return verification_results
    
    def get_summary(self):
        """Get summary of all loaded data."""
        if not self.loaded_data:
            print("No data loaded yet.")
            return {}
        
        summary = {
            'total_datasets': len(self.loaded_data),
            'total_grids': 0,
            'total_valid_labels': 0,
            'grid_shapes': set(),
            'adsorbates': set(),
            'env_adsorbate_combinations': set(),
            'zeolite_types': set(),
            'environments': set(),
            'features': None
        }
        
        for key, data in self.loaded_data.items():
            summary['total_grids'] += data['total_grids']
            summary['total_valid_labels'] += sum(1 for label in data['labels'] if label is not None)
            summary['grid_shapes'].add(str(data['grid_shape']))
            summary['adsorbates'].add(data['adsorbate'])
            summary['env_adsorbate_combinations'].add(f"{data['environment']}-{data['adsorbate']}")  # Track unique combinations
            summary['zeolite_types'].add(data['zeolite_type'])
            summary['environments'].add(data['environment'])
            
            if summary['features'] is None:
                summary['features'] = data['features']
        
        # Convert sets to lists
        for key in ['grid_shapes', 'adsorbates', 'env_adsorbate_combinations', 'zeolite_types', 'environments']:
            summary[key] = sorted(list(summary[key]))
        
        return summary
    
    def print_summary(self):
        """Print detailed summary of loaded data."""
        summary = self.get_summary()
        
        if not summary:
            return
        
        print(f"\n=== Data Summary ===")
        print(f"    Total datasets: {summary['total_datasets']}")
        print(f"    Total grids: {summary['total_grids']}")
        print(f"    Total valid labels: {summary['total_valid_labels']}")
        print(f"    Zeolite types: {summary['zeolite_types']}")
        print(f"    Environments: {summary['environments']}")
        print(f"    Environment-adsorbate combinations: {len(summary['env_adsorbate_combinations'])}")
        print(f"    Adsorbates: {summary['adsorbates']}")
        print(f"    Grid shapes: {summary['grid_shapes']}")
        if summary['features']:
            print(f"    Features ({len(summary['features'])}): {summary['features']}")
        
        # Show breakdown by environment
        print(f"\n=== Breakdown by Environment ===")
        for env in summary['environments']:
            env_combinations = [combo for combo in summary['env_adsorbate_combinations'] if combo.startswith(f"{env}-")]
            print(f"    {env}: {len(env_combinations)} adsorbates")
            # Show first few examples
            ad = [combo.split('-', 1)[1] for combo in env_combinations]  # Split only on first '-' to handle complex adsorbate names
            print(f"    Adsorbates: {ad}")
    
    def show_dataset_details(self, dataset_key=None):
        """Show detailed information about specific dataset or all datasets."""
        if dataset_key:
            datasets_to_show = [dataset_key] if dataset_key in self.loaded_data else []
        else:
            datasets_to_show = list(self.loaded_data.keys())
        
        if not datasets_to_show:
            print("No datasets to show")
            return
        
        print(f"\n=== Dataset Details ===")
        for key in datasets_to_show:
            data = self.loaded_data[key]
            
            print(f"\n--- Dataset: {key}")
            print(f"    Adsorbate: {data['adsorbate']}")
            print(f"    Environment: {data['environment']}")
            print(f"    Zeolite type: {data['zeolite_type']}")
            print(f"    Grid shape: {data['grid_shape']}")
            print(f"    Total grids: {data['total_grids']}")
            print(f"    Original snapshots: {data['snapshots_count']}")
            
            # Label statistics
            valid_labels = sum(1 for label in data['labels'] if label is not None)
            print(f"    Valid labels: {valid_labels}/{len(data['labels'])}")
            
            if valid_labels > 0:
                valid_label_values = [label for label in data['labels'] if label is not None]
                print(f"    Label range: [{min(valid_label_values):.3f}, {max(valid_label_values):.3f}]")
            
            # Show unique snapshot indices
            unique_snapshots = sorted(set(data['snapshot_indices']))
            print(f"    Snapshot indices: {unique_snapshots}")

            # Show grids per snapshot
            snapshot_counts = {}
            for snap_idx in data['snapshot_indices']:
                snapshot_counts[snap_idx] = snapshot_counts.get(snap_idx, 0) + 1
            
            print(f"    Grids per snapshot:")
            for snap_idx in sorted(snapshot_counts.keys()):
                print(f"        Snapshot {snap_idx}: {snapshot_counts[snap_idx]} grids")
            
            # Show voxel_id range
            if 'voxel_ids' in data:
                unique_voxel_ids = sorted(set(data['voxel_ids']))
                print(f"    Voxel IDs (rotation indices): {unique_voxel_ids[:5]}...{unique_voxel_ids[-5:]} (range: {min(unique_voxel_ids)}-{max(unique_voxel_ids)})")
    
    def clear_cache(self):
        """Clear loaded data from memory."""
        self.loaded_data.clear()
        self.all_pickle_files.clear()
        self.feature_names = None  # Reset feature names
        if self.verbose:
            print("Data cache cleared")


if __name__ == "__main__":
    print("=== VoxelGridsLoader Demo ===")
    
    ############# TESTING PARAMETERS #############
    test_code = True    # True for one selected dataset, False for full dataset
    test_zeolite = 'FAU'
    test_environment = 'methanol_240_water_960-hydrophilic'
    test_adsorbate = '02_01_02_propanol'
    ##############################################

    if test_code:
        zeolite_types = [test_zeolite]
        adsorbates_by_env = {test_environment: [test_adsorbate]}
        print("    Running in TEST mode with one selected dataset")
        print(f"    Zeolite: {test_zeolite}")
        print(f"    Environment: {test_environment}")
        print(f"    Adsorbate: {test_adsorbate}")
    else:
        zeolite_types = ZEOLITE_TYPES
        adsorbates_by_env = ADSORBATES_BY_ENV
        print("    Running with FULL dataset")
    
    print(f"    Environments to load: {list(adsorbates_by_env.keys())}")
    
    # Initialize loader
    loader = VoxelGridsLoader(
        zeolite_types=zeolite_types,
        adsorbates_by_env=adsorbates_by_env,
        box_grids_size=16.0,
        box_increment=0.8,
        num_features=28,
        verbose=True
    )
    
    # Load label data (optional - for reference)
    df_labels = loader.load_label_data()
    
    # Load all pickle files
    loaded_data = loader.load_all_pickle_files()
    
    # Verify data integrity
    verification_results = loader.verify_loaded_data()

    # Get feature names
    feature_names = loader.feature_names
    
    # Print summary
    loader.print_summary()
    
    # Show detailed information
    if test_code:
        dataset_key = f"{test_zeolite}-{test_environment}-{test_adsorbate}"
        loader.show_dataset_details(dataset_key=dataset_key)
